language: ruby
rvm:
  - 2.5.3

# To use Bundler 2.0+, update bundler
# per https://docs.travis-ci.com/user/languages/ruby/
before_install:
  - gem update --system
  - gem install bundler

script: 
  - bundle exec jekyll build
# If we want to check our website too, uncomment the line below
# - ./_script/htmlproofer.sh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

