# Site settings
title: Pioneers in Engineering
email: leadership@pioneers.berkeley.edu
copyright: >
  Â© Pioneers in Engineering Foundation 2019.
license: >
  This work is licensed under a
  <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
baseurl: "https://github.com/Fylthy-Cazual/website" # the subpath of your site, e.g. /blog/
url: "Fylthy-Cazual.github.io" # the base hostname & protocol for your site
permalink: /blog/:year/:month/:day/:title
twitter_username: PieRobotics
github_username: pioneers
facebook_username: pierobotics
youtube_username: pierobotics
instagram_username: pierobotics
host: 0.0.0.0
sponsors: /assets/sponsors/sponsorship-packet_2018-2019.pdf

# Build settings
markdown: kramdown
